# Generated by Django 5.0.1 on 2024-01-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.CharField(max_length=256)),
                ('body', models.TextField()),
                ('footer', models.TextField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
