# Generated by Django 5.0.1 on 2024-01-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
