# Generated by Django 5.0.1 on 2024-01-11 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_content_blog_date_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 17, 20, 16, 877592)),
        ),
    ]
