# Generated by Django 5.0.1 on 2024-01-15 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='Content',
            new_name='content',
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 7, 40, 56, 849228)),
        ),
    ]
